# Generated by Django 5.1.1 on 2024-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('name', models.CharField(max_length=58, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
